<?php
abstract class UserAbstract extends User{

    public $key;
    function showInfo()
    {
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo "KEY: {this->key}<br>";
    }

}