<?

class User{
    public $name;
    public $login;
    public $password;

    function __construct($name, $login, $password){
        $this->name=$name;
        $this->login=$login;
        $this->password=$password;

    }
    function __destruct(){
        echo "Пользователь ->".$this->login." - удален <br>";
    }

    function showInfo(){
        echo "<hr>Name: {$this->name}<br>";
        echo "Login: {$this->login}<br>";
        echo "Password: {$this->password}<br>";
    }


}

class SuperUser extends User {
    public $role;

    function __construct($name, $login, $password,$role)
    {
        parent::__construct($name, $login, $password);
        $this->role=$role;
    }
    function showInfo()
    {
       parent::showInfo(); // TODO: Change the autogenerated stub
       echo "Role: {$this->role}<br>";
    }

}

$user1 = new User('Иван','Ivan', 'Ivan123');
$user1->showInfo();


$user2 = new User('Петр','Petr','Petr123');
$user2->showInfo();


$user3 = new User('Василий','Vasia','Vasia123');
$user3->showInfo();

$superUser1 = new SuperUser('SUPER_User','root','toor123','admin');
$superUser1->showInfo();

abstract class UserAbstract extends User{

      public $key;
        function showInfo()
    {
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo "KEY: {this->key}<br>";
    }

}

